# Generated by Django 3.0.8 on 2020-08-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191213_1327'),
        ('accounts', '0007_order_note'),
    ]

    operations = [
    ]
