# Generated by Django 3.0.8 on 2020-08-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_user'),
        ('accounts', '0009_customer_user'),
    ]

    operations = [
    ]
