# Generated by Django 3.0.8 on 2020-08-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20200802_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profil_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
